# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2538d2cc8afcb1ac5145f1454ce3d874985b5559dc7672c7117ba89706e3ff4c38f77ae0412ef1d0763c52462eccfe91621add4ca2ab0fdafe9fa549f0aad631

test:
  secret_key_base: a14cf8325de734c6c4a4213db602de36d183288840622d2301b6549c3668aa6ec0a4257a86d5301f45cfd8d4bf5bdf0d1e092720d351d39ca4edf73e92930889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
